#installer docker :
#curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

#remove all image
#docker rm $(docker ps -a -q) && docker rmi $(docker images -q)

#demarrage du daemon :
#sudo systemctl start docker

version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=ra_user_suitecrm
      - MARIADB_DATABASE=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/bitnami/mariadb_data:/bitnami'
  suitecrm:
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=ra_user_suitecrm
      - SUITECRM_DATABASE_NAME=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=hhoareau
      - SUITECRM_PASSWORD=hh4271
      - SUITECRM_LASTNAME=hoareau
      - SUITECRM_SMTP_HOST=smtp.gmail.com
      - SUITECRM_SMTP_USER=hhoareau@gmail.com
      - SUITECRM_SMTP_PASSWORD=hh4271$$
      - SUITECRM_SMTP_PROTOCOL=TLS
      - SUITECRM_SMTP_PORT=587
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/opt/bitnami/suitecrm_data:/bitnami'
    depends_on:
      - mariadb
  proxy:
    image: 'jwilder/nginx-proxy:alpine'
    restart: always
    ports:
      - 80:80
      - 443:443
    labels: com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:r
      
  letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
          - certs:/etc/nginx/certs
          - conf.d:/etc/nginx/conf.d
          - vhost.d:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - proxy
    
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
