#installer docker :
#curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

#demarrage du daemon :
#sudo systemctl start docker

version: '2'
services:
  mariadb:
    container_name: mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=ra_user_suitecrm
      - MARIADB_DATABASE=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/opt/bitnami/mariadb_data:/bitnami'
  
  suitecrm:
    container_name: suitecrm
    image: 'bitnami/suitecrm:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - SUITECRM_DATABASE_USER=ra_user_suitecrm
      - SUITECRM_DATABASE_NAME=ra_db_suitecrm
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=hhoareau
      - SUITECRM_PASSWORD=hh4271
      - SUITECRM_LASTNAME=hoareau
      - SUITECRM_SMTP_HOST=smtp.gmail.com
      - SUITECRM_SMTP_USER=hhoareau@gmail.com
      - SUITECRM_SMTP_PASSWORD=hh4271$$
      - SUITECRM_SMTP_PROTOCOL=TLS
      - SUITECRM_SMTP_PORT=587
      - LETSENCRYPT_HOST=server.f80.fr
      - LETSENCRYPT_EMAIL=hhoareau@gmail.com
      - VIRTUAL_HOST=server.f80.fr
      - VIRTUAL_PORT=80
      
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/opt/bitnami/suitecrm_data:/bitnami'
    depends_on:
      - mariadb
      
  proxy:
    image: 'jwilder/nginx-proxy:alpine'
    restart: always
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    labels: 
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /root/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - conf.d:/etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      
  letsencrypt-companion:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /root/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    
volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
  certs:
  conf.d:
  vhost.d:
  html:
