baseURL = "https://f80dev.github.io/blogs-creches-republique_enfant/"
languageCode = "fr-fr"
title = "Le blog de maRE"
theme = "hamburg"
uglyURLs = true
canonifyURLs = true
defaultContentLanguage = "fr"
NewContentEditor = "mate"

[permalinks]
  posts = "/:year/:month/:title/"

[sitemap]
    changefreq="weekly"
    filename="sitemap.xml"
    priority=0.5
